[tool.commitizen]
name = "cz_conventional_commits"
version = "0.1.0"
tag_format = "v$version"
update_changelog_on_bump = true
version_files = [
    "VERSION",
    "setup.sh:VERSION="
]
changelog_incremental = true
changelog_file = "CHANGELOG.md"