name: Request Reviewers

on:
  pull_request:
    types: [opened]

jobs:
  request:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - run: gh pr edit ${{ github.event.pull_request.number }} --add-reviewer $REPO_OWNER --repo ${{ github.repository }}
        env:
          REPO_OWNER: ${{ github.repository_owner }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
