name: Release Please

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          # Use a PAT if GITHUB_TOKEN doesn't have permission to create PRs
          # Create a PAT with repo and workflow scopes, then add it as RELEASE_TOKEN secret
          token: ${{ secrets.RELEASE_TOKEN || secrets.GITHUB_TOKEN }}
          
          # Simple release configuration
          release-type: simple
          package-name: macbook-dev-setup
          extra-files: |
            VERSION
            setup.sh